import {Platform, StyleSheet} from 'react-native';
import {hp, wp} from '../../Config/responsive';
import {Colors} from '../../Theme/Variables';

export const styles = StyleSheet.create({
  headerView: {
    flexDirection: 'row',
    // marginTop: Platform.OS == 'ios' ? hp('6') : hp('3'),
    paddingHorizontal: wp('5'),
    paddingBottom: hp('3'),
    backgroundColor: Colors.themeRed,
    paddingTop: Platform.OS == 'ios' ? hp('6') : hp('2'),
    height: Platform.OS == 'ios' ? hp('12') : hp('8'),
    alignItems: 'center',
  },
  HeaderLeft: {
    flex: 0.2,
    // justifyContent: 'center',
    // alignItems: 'center',
    // alignContent: 'center',
  },
  arrowback: {
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    alignSelf: 'center',
    width: wp('7'),
  },
  HeaderCenter: {
    flex: 1,
    alignItems: 'center',
    // backgroundColor: 'blue',
    height: hp('5'),
    textAlignVertical: 'center',
    flexDirection: 'row',
    // marginTop: hp('3'),
  },
  HeaderRight: {
    flex: 0.5,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  backMain: {
    alignItems: 'center',
    flexDirection: 'row',
    textAlign: 'left',
    alignItems: 'flex-end',

    // backgroundColor: 'red',
  },
  senderView: isSender => ({
    width: wp('100'),
    alignItems: 'flex-end',
    flexDirection: 'row',
    marginVertical: hp('1.5'),
    marginLeft: isSender ? 0 : wp('2'),
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 5,
    elevation: 50,
    // justifyContent: 'flex-end',
  }),
  senderText: isSender => ({
    maxWidth: wp('80'),
    borderWidth: 0.3,
    borderColor: Colors.grayFaded,
    borderTopEndRadius: 15,
    borderTopStartRadius: 15,
    borderBottomEndRadius: isSender ? 0 : 15,
    borderBottomStartRadius: isSender ? 15 : 0,
    paddingVertical: hp('1.5'),
    paddingHorizontal: wp('3.5'),
    marginRight: isSender ? wp('2') : 0,
    backgroundColor: isSender ? Colors.themeRed : 'transparent',
    lineHeight: 100,
  }),
  msgsRecieve: {
    paddingHorizontal: wp('4'),
    flexDirection: 'row',
    alignItems: 'center',
  },
  sendIcon: {
    width: wp('5'),
    height: hp('3'),
    resizeMode: 'contain',
    marginLeft: wp('1'),
  },
  searchMain: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    minHeight: hp('7'),
    maxHeight: hp('14'),
    // height: 'auto',
    borderRadius: 10,
    borderColor: Colors.lightBlack,
    paddingHorizontal: wp('1.8'),
    // marginHorizontal: wp('4'),
    // marginVertical: hp('2'),
    overflow: 'hidden',
    marginBottom: Platform.OS == 'ios' ? hp('1') : hp('0'), // justifyContent: 'center',
    backgroundColor: Colors.themeBlack,
  },
  searchinput: {
    // paddingHorizontal: wp(''),
    // width: wp('65'),
    paddingRight: wp('3'),
    fontSize: hp('2'),
    flex: 1,
    color: 'white',
  },
  sendBtnStyle: {
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: Colors.themeRed,
  },
  sendTextStyle: {
    color: 'white',
    marginLeft: wp('1.5'),
    paddingVertical: hp('1.3'),
    // paddingHorizontal: wp('3'),
  },
  upperButton: {
    width: wp('100'),
    alignItems: 'center',
    paddingHorizontal: wp('5'),
    flexDirection: 'row',
    borderBottomWidth: 1.5,
    borderBottomColor: Colors.lightBlack,
    justifyContent: 'space-between',
  },
});
