import {hp, wp} from '../../Config/responsive';

const {StyleSheet, Platform} = require('react-native');
const {Colors} = require('../../Theme/Variables');

export const styles = StyleSheet.create({
  headerView: {
    backgroundColor: Colors.themeRed,
    width: wp('100'),
    paddingTop: Platform.OS == 'ios' ? hp('2') : 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp('2'),
    paddingBottom: hp('2'),
  },
  firstView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Platform.OS == 'ios' ? hp('2') : hp('-2'),
    alignSelf: 'center',
    // paddingBottom: hp('2'),
    maxWidth: wp('80'),
  },
  nameText: {
    fontSize: hp('2.5'),
    fontWeight: 'bold',
    marginTop: hp('2.5'),
  },
  notiIcon: {width: wp('7')},
  setIcon: {width: wp('7')},
  headingView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp('94'),
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
    marginTop: hp('3'),
  },
  comingView: {
    width: wp('90'),
    borderRadius: 6,
    borderWidth: 0.2,
    borderColor: Colors.grayFaded,
    // height: hp('10'),
    // paddingVertical: hp('2'),
    // paddingHorizontal: wp('3'),
    marginLeft: hp('1.5'),
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 5,
    elevation: 50,
    backgroundColor: Colors.themeBlack,
    height: hp('22'),
    // backgroundColor: 'white',
  },
  upperView: {flexDirection: 'row', alignItems: 'center'},
  locationView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp('1.5'),
    marginLeft: wp('1.5'),
  },
  locationIcon: {width: wp('75'), fontSize: hp('1.7'), marginLeft: wp('1')},
  divider: {width: wp('70'), marginTop: hp('1'), marginLeft: wp('1')},
  bottomView: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginLeft: wp('2'),
    // marginTop: hp('1'),
    width: wp('90'),
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    height: hp('5'),
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    justifyContent: 'center',
    paddingHorizontal: wp('0'),
    // borderRadius: 10,
  },
  dateText: {
    fontSize: hp('1.8'),
    marginLeft: wp('2'),
    marginRight: wp('5'),
    color: 'white',
  },
  timeText: {
    fontSize: hp('1.8'),
    marginLeft: wp('2'),
    color: 'white',
  },
  upComingFlatlistView: {
    height: hp('25'),
    alignItems: 'center',
    paddingRight: wp('4'),
  },
  bookBtnView: {
    backgroundColor: 'white',
    width: wp('90'),
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  btnImage: {
    tintColor: 'red',
    width: wp('20'),
    height: hp('3'),
    marginRight: wp('-2'),
  },
  btnText: {color: 'black', fontWeight: 'bold', marginLeft: wp('4')},
  topRatedView: {
    paddingRight: wp('3'),
    paddingLeft: wp('3'),
    marginTop: hp('2'),
  },
  userView: {
    flexDirection: 'row',
    width: wp('90'),
    paddingHorizontal: wp('2'),
    marginTop: hp('1'),
  },
  nameView: {marginLeft: wp('2'), justifyContent: 'space-between'},
  infIcon: {
    width: wp('6'),
    height: hp('5'),
    marginLeft: wp('1'),
  },
  viewBtnView: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: hp('2'),
    alignItems: 'center',
  },
  viewAppBtn: {
    backgroundColor: Colors.lightBlack,
    width: wp('70'),
    height: hp('5'),
  },
  profileView: {
    width: wp('93'),
    alignSelf: 'center',
    backgroundColor: 'white',
    // height: hp('14'),
    borderRadius: 10,
    paddingVertical: hp('1'),
    paddingHorizontal: wp('3'),
    flexDirection: 'row',
    marginTop: hp('5'),
  },
  pViewHeading: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: hp('2.5'),
    marginTop: hp('1.5'),
  },
  pViewText: {
    width: wp('60'),
    color: Colors.textGray,
    fontSize: hp('1.5'),
    marginTop: hp('1'),
  },
  Per: {color: 'black', fontSize: hp('3'), fontWeight: 'bold'},
});
